name = "PostTensorBoard"
uuid = "876a9d29-178b-4c49-a70d-890c5e524a1b"
authors = ["dhtan <dinghangtan@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
